name: GHAs-fmt

on:
  pull_request:
    branches: GHAs-fmt
  push:
    branches: GHAs-fmt

jobs:
  check-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check GitHub variables
        run: |
          echo ${{ github.repository }}
          echo ${{ github.branch }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.head.repo.full_name }}
          echo ${{ github.event.pull_request.base.repo.full_name }}
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install minimal stable with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: Run rustfmt
      uses: actions-rs/cargo@v1.0.1
      with:
        command: fmt
    - name: Commit fmt files
      run: |
        git config --local user.email "ravinderjangra@live.com"
        git config --local user.name "Ravinder Jangra"
        git commit -m "chore(rustfmt): add rustfmt changed" -a
        git remote -v
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        resposity: 'S-Coyle/safe-api'
        branch: ${{ github.head_ref }}
